# The URL the site will be built for
# base_url = "https://pinkhatbeard.com"
base_url = "https://cldershem.gitlab.io/testgutenberg"
title = "phb"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
highlight_theme = "monokai"

generate_tags_pages = true
generate_rss = true

[extra]
# Put all your custom variables here
taggers = ["1", "3"]
